spring:
  application:
    name: EmployeeService
server:
  port: 8081 

springdoc:
  api-docs:
    enabled: ${ENABLE_SWAGGER_UI:true}
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true  # Ensure this property is added and set to true
